name: Update GitHub Stats

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  build:
    name: Update-GitHub-Stats
    runs-on: ubuntu-latest
    env:
      GH_LOGIN: torresflo
      MARKDOWN_FILE: ../README.md

    steps:
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Clone and run GitHub-Stats
        run: |-
          git clone https://github.com/torresflo/GitHub-Stats-Me.git
          cd GitHub-Stats-Me/ && python main.py
          cd ../ && rm -rf GitHub-Stats-Me/
      - name: Commit and push
        run: |-
          git config --global user.email "bot@github.com" && git config --global user.name "GitHub-Stats-Bot"
          git config --global pull.rebase false
          git diff
          git add README.md && git commit -m "Update GitHub Stats" || exit 0
          git pull && git push